def _fail(self, msg: str):
    print(msg)
    exit()
